### PR TITLE
add dark mode

### PR DESCRIPTION
**Pull request by elijah-wright**

### CODE REVIEW

**Comment by alexng353** [comment]
There must be a way to do this in NextJS without using JS in a string...

**Comment by elijah-wright** [comment]
we want to achieve a few things with dark mode, and `dangerouslySetInnerHTML` isn't off the table if it means achieving these:
1. no white flash
2. toggling
3. no blocked rendering
4. no errors

**Comment by alexng353** [comment]
> `dangerouslySetInnerHTML` isn't off the table if it means achieving these:

Are you absolutely certain that this is the only way to do it?

I would heavily prefer not to use *any* `dangerouslySetInnerHTML` at all.

**Comment by elijah-wright** [comment]
I'm open to other ideas. but, like I said, `dangerouslySetInnerHTML` is "dangerous" because of DOM injection vulnerabilities. React deliberately chose a name like that to make people reconsider using it for things like Markdown renderers. if you're just inserting a string, I don't see an issue.

here, `dangerouslySetInnerHTML` is a way to insert the dark mode script. Next.js has an [inline script optimization](https://nextjs.org/docs/app/building-your-application/optimizing/scripts#inline-scripts) process, but that won't work here because it defers until Next.js loads IIRC

**Review by alexng353 — APPROVED** [review]

**Pull request merged**
