### PR TITLE
Latex, Image, and Audio uploads

### PR DESCRIPTION
**Pull request by manningwu07**
To do:
- Mobile design (Im gonna make someone else do this cuz this is a waste of time for me)
- Styling - currently its pretty rushed because functionality is the priority right now

### CODE REVIEW

**Comment by manningwu07** [comment]
There are practically 0 tests for edge cases, so please extensively review this code.

**Comment by BrilliantDeviation7** [comment]
Right now, the article just always saves to '/article-creator.' Because there aren't any articles right now, there needs to be a way to create a **new** article.

**Comment by BrilliantDeviation7** [comment]
There is also a bug with LaTeX where the fraction bar is gray:
image

**Comment by manningwu07** [comment]
> Right now, the article just always saves to '/article-creator.' Because there aren't any articles right now, there needs to be a way to create a **new** article.

I dont know what you mean by this; if the firebase doesnt contain an article, then it will create one on its own I believe.

**Comment by manningwu07** [comment]
> > Right now, the article just always saves to '/article-creator.' Because there aren't any articles right now, there needs to be a way to create a **new** article.
> 
> I dont know what you mean by this; if the firebase doesnt contain an article, then it will create one on its own I believe.

yea this should not be an issue...

**Comment by manningwu07** [comment]
> Right now, the article just always saves to '/article-creator.' Because there aren't any articles right now, there needs to be a way to create a **new** article.

resolved; updated firebase rules onto the code (was not aligned with what my actual firebase rules are)

**Comment by manningwu07** [comment]
> There is also a bug with LaTeX where the fraction bar is gray: image

resolved

**Review by brainlame — APPROVED** [review]

**Pull request merged**
