### PR TITLE
Created question renderer component (Check for understanding)

### PR DESCRIPTION
**Pull request by manningwu07**
This cannot be used for quizzes on its own unless you wish to expose the answers right after (and disable the retry button). However, most of the framework is there and you can just tweak it to make the react component into a test format, but for now I think this is solid.

PS Please work or else im going to cry. Vercel deployment fails but looking abck at other PRs, it seems that others have failed deployments too so im going to ignore that.

### CODE REVIEW

**Review by sresri2 — CHANGES_REQUESTED** [review]
I know you said it's just a start, looks mostly good. A few things I noticed that would need to be fixed: 

1) "Next Question", "Previous Question" styling doesn't seem to work. It just renders at text with no formatting or styling. See below image. 
Screenshot 2024-08-03 at 11 46 14 PM

2. When I reveal the correct answer for a question, then press next, it doesn't switch the state back to showing answers without revealing the correct answer. Meaning if I answer question 1, it will reveal the correct answer. Then I press next question, and it directly shows the correct answer for question 2 instead of switching the state back to just answer choices without revealing the correct answer. See below image.
Screenshot 2024-08-03 at 11 48 44 PM


3. Like you already said, we might need to adjust it to reveal answers at the end, but I think it can be used for multiple parts of the site with some adjustment (quizzes, questions in articles, digital testing portal, etc...).

**Comment by manningwu07** [comment]
I never wrote "previous question" "next question" in my code...

**Comment by manningwu07** [comment]
New update - I created 2 components: one for tests and one for "check for understanding". So the "check for understanding" is like within an article to see if the user got the concept. Theres a retry button and an indication of what you got correct or incorrect. The quiz component has multiple questions; its pretty basic right now but others can add certain features - eg show correct or like have a star/fireworks or something if user gets 100%.

**Comment by manningwu07** [comment]
Also, since the 2 components are very similar because the main UI is practically the same, I believe someone else whos more experienced can create higher ordered components in order to simplfy and abstract large parts of the code.

**Comment by manningwu07** [comment]
Screenshot 2024-08-05 at 1 32 17 PM
Screenshot 2024-08-05 at 1 31 58 PM
Screenshot 2024-08-05 at 1 31 49 PM


Screenshot 2024-08-05 at 1 32 14 PM

**Review by sresri2 — APPROVED** [review]
### Preview Review Comments:
1. I have no idea where they came from, your code definitely doesn't contain the Next and Previous buttons....
2. Same as above, so never mind. 
3. Functionality looks good. Tested the quiz renderer and question renderer. 

### Some other comments:
- I think a few UI changes would be good. Minor things like you mentioned on the UI. For example, the score is always red, but maybe it should match the percent score they got (green for 100%, yellow for middle, etc...). 

### Features:
1. One thing I think we might want is a summary screen on the quiz renderer - The review process after finishing the quiz looks good. A summary screen can show all their questions with what they answered and correct answers at the same time. They can also see their score. If we save scores to the database, it also makes it easier to pull that when needed if they come back to the same quiz. 

2. Another feature we could implement are (at least a component for) explanations. For history questions it's probably fine, but for Math or Science we might need a section in the question renderer for answer explanations. 

Overall, I think this can be merged. One concern though, **not sure if we want to merge firebase in yet and this PR contains firebase setup**. A few features and minor changes can also be made in the future. But I think this works really well and can be pushed to main.

**Pull request merged**
