### PR TITLE
alex/modify eslintrc

### PR DESCRIPTION
**Pull request by alexng353**
Feel free to suggest changes to the eslintrc before merging.

### CODE REVIEW

**Comment by flatypus** [comment]
Personal vouch: sorted + grouped imports? 

https://github.com/import-js/eslint-plugin-import
image

**Comment by elijah-wright** [comment]
the `next/core-web-vitals` config, which is an extension of `eslint-plugin-next` that includes rules that error when Core Web Vitals are affected, is pretty good already. two adjustments:
1. you mentioned this, but `no-unused-vars` errors on parameters in interface declarations. `@typescript-eslint/no-unused-vars` is better, and we should define an underscore as `varsIgnorePattern`
2. `react-hooks/exhaustive-deps` is [good to have](https://github.com/facebook/create-react-app/issues/6880#issuecomment-485912528) to ensure useEffect is used properly

**Comment by alexng353** [comment]
> react-hooks/exhaustive-deps

Yes I can add react eslint plugin to this

**Comment by alexng353** [comment]
> Personal vouch: sorted + grouped imports?

This is coming.

**Comment by alexng353** [comment]
Proposal: https://github.com/jsx-eslint/eslint-plugin-jsx-a11y

**Comment by alexng353** [comment]
> 2\. `react-hooks/exhaustive-deps` is [good to have](https://github.com/facebook/create-react-app/issues/6880#issuecomment-485912528) to ensure useEffect is used properly

**Comment by alexng353** [comment]
> * you mentioned this, but `no-unused-vars` errors on parameters in interface declarations. `@typescript-eslint/no-unused-vars` is better, and we should define an underscore as `varsIgnorePattern`

I've added the `varsIgnorePattern`.

**Pull request closed without merging**
